cd "todos os times"
md "serie A" 
cd "serie A"
md "Atletico MG"	
md "Palmeiras"	
md "Fortaleza"	
md "Bragantino"	
md "Flamengo"	
md "Athletico PR"	
md "Atletico Go"	
md "Ceara"	
md "Internacional"	
md "Santos"
md "Corinthians"	
md "Juventude"	
md "Bahia"	
md "Sao Paulo"	
md "Fluminense"	
md "Cuiaba"
md "Sport"
md "America"	
md "Gremio"
md "Chapecoense"	